### ISSUE TITLE
`N` and `M` flipped

### ISSUE THREAD

**Issue by JacobHelwig** [alasdairtran/fourierflow#7]
I think that `N` and `M` need to be flipped in the following lines.

https://github.com/alasdairtran/fourierflow/blob/505f4b98a9a96c5fe25bbb0f87792bf1dcd946da/fourierflow/modules/factorized_fno/grid_2d.py#L61

https://github.com/alasdairtran/fourierflow/blob/505f4b98a9a96c5fe25bbb0f87792bf1dcd946da/fourierflow/modules/factorized_fno/grid_2d.py#L79

This only becomes clear when considering `N!=M`.

**Comment by alasdairtran** [comment]
Good catch! I've pushed a fix in d60eb57161897473ccdf8abb83beaa46b0d88889 

All of the regular grids used in the experiments have N=M so this shouldn't affect the existing results.

Thanks!
