### ISSUE TITLE
Question about deepcopy in your code

### ISSUE THREAD

**Issue by BraveDrXuTF** [alasdairtran/fourierflow#8]
Thank you for your excellent work! So I want to ask a question about deepcopy. Why does deepcopy used in the experiments, I notice that you also modify the nn.Linear code to let the weight norm can be deepcopied.

**Comment by alasdairtran** [comment]
I think at that time, I was experimenting with [StochasticWeightAveraging](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.StochasticWeightAveraging.html), which requires all modules to support `deepcopy`. SWA ended up not making any difference to the performance, so I dropped that approach but didn't remove deepcopy code.

**Comment by BraveDrXuTF** [comment]
😃Got it.
